name: Build and deploy Node.js app to AWS Web App - MTAserverApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22  # If different from default 22
          script: |
            cd code-analyzer
            git pull
            npm install
            if pm2 describe Server | grep -q 'stopped'
            then
              pm2 start Server.js
            else
              pm2 restart Server
            fi
            cd .. && cd react && npm install && export PORT=5000
            if pm2 describe React | grep -q 'stopped'
            then
              pm2 start npm -- start
            else
              pm2 restart React
            fi


