name: Build and deploy Node.js app to AWS Web App - MTAserverApp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22 # Default port
          script: |
            cd Code-Analyzer
            rm .env
            git reset --hard
            git clean -fd
            git pull
            npm install
            if pm2 describe Server | grep -q 'online\|stopped'
            then
              pm2 restart Server
            else
              pm2 start npm --name "Server" -- run start
            fi
            cd react/app && npm install && export PORT=5000
            if pm2 describe React | grep -q 'online\|stopped'
            then
              pm2 restart React
            else
              pm2 start npm --name "React" -- run start
            fi

      - name: Create .env file
        run: |
              echo "CALLBACK_URL=${{ secrets.CALLBACK_URL }}" >> .env
              echo "GIT_HUB_CLIENT_ID=${{ secrets.GIT_HUB_CLIENT_ID }}" >> .env
              echo "GIT_HUB_CLIENT_SECRET=${{ secrets.GIT_HUB_CLIENT_SECRET }}" >> .env
              echo "OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}" >> .env
              echo "REACT_PORT=${{ secrets.REACT_PORT }}" >> .env
              echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
    
      - name: Copy .env file to server
        uses: appleboy/scp-action@v0.1.1
        with:
              host: ${{ secrets.SSH_HOST }}
              username: ${{ secrets.SSH_USER }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              source: ".env"
              target: "/Code-Analyzer/.env"


