name: Build and deploy Node.js app to Azure Web App - MTACodeAnalyzer

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: cd NodeJs && npm install

      - name: Build and test
        run: |
          cd NodeJs
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip -r release.zip NodeJs/*

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: Unzip artifact
        run: unzip release.zip -d NodeJs

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MTACodeAnalyzer'
          slot-name: 'Production'
          package: NodeJs
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_D71D554B8EB441CE9764B8B38405D708 }}
